package com.riicarus.comandante.executor;

/**
 * [FEATURE INFO]<br/>
 * The executor generated by grammar analyzer provided to command dispatcher to execute.
 *
 * @author Riicarus
 * @create 2023-4-17 22:56
 * @since 3.0
 */
public class GeneratedExecutor {
    /**
     * Used to provide simple lambda expression for execute the command's analyzed executors.
     */
    private final GeneratedExecutable exe;

    public GeneratedExecutor(GeneratedExecutable exe) {
        this.exe = exe;
    }

    public void execute() throws Exception {
        this.exe.execute();
    }

    public interface GeneratedExecutable {
        void execute() throws Exception;
    }
}
